<?php

namespace App\Services;

use App\Repositories\Contracts\StudentRepositoryInterface;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Services\ApiGatewayService;
use App\Models\Tenant;
use Illuminate\Support\Facades\DB;
use App\Jobs\SendWelcomeEmailJob;

class StudentService
{
    protected $repo;
    protected $userRepo;

    public function __construct(StudentRepositoryInterface $repo,UserRepositoryInterface $userRepo)
    {
        $this->repo = $repo;
        $this->userRepo = $userRepo;
    }

    public function getStudents($dataPass)
    {
        $fields = ApiGatewayService::selectFields([
            "users.id as user_id",
            "students.id as student_id",
            "users.name as student_name",
            "students.status",
            "students.admission_no",
            "students.class_id",
            "students.section",
            "students.parent_phone",
        ]);
        $dataPass['fields'] = $fields;
        $studentData = $this->repo->all($dataPass);

        return $studentData;
    }

    public function createStudent(array $data)
    {
        DB::beginTransaction();

        try {

            $tenantId =  auth()->user()->tenant_id;
            $tenantDomain = $tenantDomain = Tenant::find($tenantId)->subdomain ?? null;
            $autoGeneratedAdmNo = $this->generatedAdmissionToken($tenantDomain);

            // 1) Create USER
            $user = $this->userRepo->createUser([
                'tenant_id'   => $tenantId,
                'name'        => $data['name'],
                'email' => $data['parent_email'],
                'phone'       => $data['parent_phone'] ?? null,
            ]);

            if (!$user) {
                DB::rollBack();
                return ['status' => false, 'message' => 'User creation failed'];
            }

            // !empty($adminId) ? $this-> api
            // 2) Create STUDENT
            $student = $this->repo->createStudent([
                'user_id'      => $user->id,
                'admission_no' => $autoGeneratedAdmNo,
                'class_id'     => $data['class_id'],
                'section'      => $data['section'],
                'dob'          => $data['dob'],
                'gender'       => $data['gender'],
                'parent_name'  => $data['parent_name'],
                'parent_email' => $data['parent_email'],
                'parent_phone' => $data['parent_phone'],
                'address'      => $data['address'],
                'tenant_id'   => $tenantId,

            ]);

            if (!$student) {
                DB::rollBack();
                return ['status' => false, 'message' => 'Student creation failed'];
            }

            SendWelcomeEmailJob::dispatch($user->id);

            DB::commit();

            return [
                'status'  => true,
                'message' => 'Student created successfully',
                'user'    => $user,
                'student' => $student
            ];

        } catch (\Exception $e) {
                DB::rollBack();

                return [
                    'status' => false,
                    'message' => 'Something went wrong',
                    'error'   => $e->getMessage()
                ];
        }
    }

    protected function generatedAdmissionToken($tenantDomain){
        $randumNumber = $tenantDomain.'-'.rand(100000, 999999);
        return $this->repo->isAdmissionNoExists($randumNumber) ? $this->generatedAdmissionToken($tenantDomain): $randumNumber;
    }
}
